### ISSUE TITLE
v2.0

### ISSUE THREAD

**Issue by obetomuniz** [minasdev/minasdev.org#12]
### Site
- [x] Uma seção de Sobre mais evidente
  - Trabalhar mais este assunto para deixar mais evidente o que é o Minas Dev (Leia-se [Manifesto](https://github.com/minasdev/manifesto#minas-dev-manifesto))(https://github.com/anapaulagomes/meetups-analysis/tree/master/dados/grupos)
- [x] Blog do Minas Dev que vão utilizar a estrategia de Retweets do Twitter do Minas Dev para gerar volume de conteúdo.
- [x] Listagem de Comunidades, Grupos e Eventos integrados pelo Minas Dev
 - (Adicionar call to action "Seu meetup ou evento não está ai? Adicione aqui")
- [x] Evidenciar com uma Call to Action que todos podem/devem também colaborar com o conteúdo da Newsletter
- [x] Site Responsivo
- [x] Refatorar site para utilização da metodologia BEM para CSS
- [x] Implementar CD.

E por hora, são essas as considerações.

<small>[issue em construção]</small>

**Comment by pedrochaves** [comment]
O que cês acham de criar um código de conduta pro MinasDev? Poderia se extender para os eventos organizados e comunidades que ele apoia. Aí teria um link no site pra ele.

Exemplo do PHPMG: https://github.com/phpmg/documentos/blob/master/codigo-de-conduta.md

**Comment by brunopulis** [comment]
@pedrochaves Acho bastante interessante!

**Comment by obetomuniz** [comment]
Acho interessante sim, porém não somos uma comunidade como o PHP-MG e sim uma iniciativa, ou seja, não é tão tangível, porém podemos fazer um Código de Conduta geral de comportamento em comunidade e que reflita em nossos preceitos filosóficos.

**Comment by paulohp** [comment]
Poderia ter um blog tbm, onde poderemos reproduzir textos nossos e escrever novos relacionados a comunidade, fazer cobertura de eventos e etc.

Iria ser legal tbm uma especie de channel no youtube (nada formal ou com periodicidade), onde faríamos entrevistas com os membros, pessoas que atuam na comunidade local e etc.

 Nao sei se seria relacionado ao assunto pertinente, mas é um `keep in mind` legal e eu posso ficar responsavel por ambas.

**Comment by obetomuniz** [comment]
@paulohp Interessante isso mesmo, e na sua ideia, colocar isso é o caso de agregar junto ao Indexador de Artigos? Ou algo separado?

**Comment by pedrochaves** [comment]
@obetomuniz, a ideia de juntar o código de conduta com o manifesto é uma boa. A ideia do código de conduta do MinasDev é mais pra ser uma referência mesmo. Seria usado nos eventos organizados pelo MinasDev (devbeers, dev in company) e poderia ser extendido para as outras comunidades caso elas quisessem. Talvez só mantê-lo disponível para fork, por exemplo.

**Comment by paulohp** [comment]
Pode ser junto mesmo @obetomuniz.

**Comment by obetomuniz** [comment]
@paulohp @pedrochaves @brunopulis Atualizei a descrição da Issue com o link do documento que vamos extrair para criar o Manifesto e também com a sugestão do Blog do Minas Dev conjunto com a indexação de artigos

**Comment by brunopulis** [comment]
@obetomuniz Show de bola :D @paulohp Gostei da sua sugestão do channel do Youtube e blog.

**Comment by pedrochaves** [comment]
@obetomuniz :+1:

:+1: pra sugestão do blog do @paulohp também

**Comment by pedrommone** [comment]
:+1: pra sugestão do @paulohp, mas, acredito que um agregador seria mais viável, por causa do tempo pra fazer os textos, e/ou se não tiver galera suficiente pra manter o blog vivo.
