### ISSUE TITLE
Como contribuir

### ISSUE THREAD

**Issue by brunopulis** [minasdev/minasdev.org#14]
Creio que seja interessante criamos uma sessao no README de como contribuir e enviar os PR's para o MD.

**Comment by obetomuniz** [comment]
Boa @brunopulis! O que acha desse modelo? https://github.com/obetomuniz/autocomplete-semantic-web/blob/master/contributing.md

**Comment by brunopulis** [comment]
@obetomuniz Acho excelente!

**Comment by obetomuniz** [comment]
Prontinho @brunopulis! 🥂
